package DispenserController {

  class Dispenser{
    uint8_t executeCommand(String command)
    void UARTHandler()
    void initializeHandlers()
    void commandSuccess()
    void commandFailure()   
    void proximitySensorTriggered()
    void treatRequested()
    
  }

  class Sensor{
      void ISR_Handler_sensor()
      void sensorTriggered()
  }
}

Dispenser -> Sensor