@startuml FoodGiver
package SystemController{

  class SystemManager{
    - CommandController cmdCtrl
    - Setting currentSetting
    + void runSystem()
    - void listenSettingsUpdate()
    - void mainThread()
  }

  class CommandController{
    - MsgQueue * msg
    - CommandQueue commandQueue
    - PsocComm psoc
    - WebComm web
    + initialize(MsgQueue * msg)
    + int dispatchNextCommand()
    + void addCommand(String cmd)
  }

  class CommandQueue{
    - list<String> fifoQueue
    + String getNextCommand()
    + void insertCommand(String cmd)
  }

  class PsocComm{
    - bool connected
    + int checkPsocConnection()
    + int relayCommand(String command)
    + void uartListenerThread(MsgQueue * msg)
    - void sendUART(String command)
    - void receiveUART()

  }

  class WebComm{
    - bool connected
    + int connectToServer()
    + void makeRequestThread(MsgQueue * msg)
    - void createTCPSocket()
    - void sendTCPMessage()
    - void receiveTCPMessage()
  }

  class Setting{
    - list<int> feedingTimes
    - int foodAmount
    - bool treatsEnabled
    - bool treatRequestsEnabled
    - int treatLimit
    + int getFoodAmount()
    + list<int> getFeedingTimes()
    + bool getTreatsEnabled()
    + bool getTreatRequestsEnabled()
    + int getTreatLimit()
  }
}




CommandController *- CommandQueue
SystemManager *-- Setting
PsocComm -* CommandController
WebComm --* CommandController


CommandController --* SystemManager

@enduml
